In [1]:
import numpy as np

first_array = np.array([1,2,3,0])
second_array = np.array([4,1,0,6])
addition = first_array + second_array
subtraction = first_array - second_array
multiplication = first_array * second_array
division = first_array / second_array
print("Addition is:-")
print(addition)
print("Subtraction is:-")
print(subtraction)
print("Multiplication is:-")
print(multiplication)
print("Division is:-")
print(division)

Addition is:-
[5 3 3 6]
Subtraction is:-
[-3  1  3 -6]
Multiplication is:-
[4 2 0 0]
Division is:-
[0.25 2.    inf 0.  ]


C:\Users\sdas9\AppData\Local\Temp\ipykernel_1492\2041302985.py:8: RuntimeWarning: divide by zero encountered in divide
  division = first_array / second_array


In [2]:
import numpy as np

first_array = np.random.randint(1, 101, 5)
second_array = np.random.randint(1, 101,20).reshape(4,5)

# Performing addition
addition = second_array + first_array

# Performing subtraction
subtraction = second_array - first_array

print("1-D array is:-")
print(first_array)
print("2-D array is:-")
print(second_array)
print("Addition is:-")
print(addition)
print("Subtraction is:-")
print(subtraction)

1-D array is:-
[49 73 73 53 75]
2-D array is:-
[[56 81 57 99 83]
 [21 25 98 81 93]
 [69  2 79 94 52]
 [49 82 51 45 36]]
Addition is:-
[[105 154 130 152 158]
 [ 70  98 171 134 168]
 [118  75 152 147 127]
 [ 98 155 124  98 111]]
Subtraction is:-
[[  7   8 -16  46   8]
 [-28 -48  25  28  18]
 [ 20 -71   6  41 -23]
 [  0   9 -22  -8 -39]]


In [3]:
import numpy as np

array_three_d = np.random.randint(1, 101,27).reshape (3, 3, 3)

second_d_third_column = array_three_d[1, :, 2]
first_d_first_row_third_row = array_three_d[0, [0, 2], :]
third_d_intersection_first_row_third_column = array_three_d[2, 0, 2]

print("3-D array is :-")
print(array_three_d)
print("Third column of second 2-D array is :-")
print(second_d_third_column)
print("First and third row of first 2-D array is :-")
print(first_d_first_row_third_row)
print("Intersection of first row and third column in third 2-D array is :-")
print(third_d_intersection_first_row_third_column)

3-D array is :-
[[[46 33 24]
  [57 69 89]
  [32 39 19]]

 [[67 44 21]
  [68 99 59]
  [73 30 32]]

 [[51 60 71]
  [85 48 77]
  [94 76 58]]]
Third column of second 2-D array is :-
[21 59 32]
First and third row of first 2-D array is :-
[[46 33 24]
 [32 39 19]]
Intersection of first row and third column in third 2-D array is :-
71


In [4]:
import numpy as np

random_matrix = np.random.randint(1, 101,20).reshape(5, 4)
print("Original 2-D Array:-\n", random_matrix)

even_number = random_matrix[random_matrix % 2 == 0]
print("Even Numbers:-\n", even_number)

odd_number = random_matrix[random_matrix % 2 != 0]
print("Odd Numbers:-\n", odd_number)

row_sum = random_matrix.sum(axis = 1);
print("Row-wise Sum:-\n", row_sum)

column_sum = random_matrix.sum(axis = 0);
print("Column-wise Sum:-\n", column_sum)

three_d = random_matrix.reshape(2,2,5)
print("3D Array:-\n", three_d)

Original 2-D Array:-
 [[ 34  50  56 100]
 [ 65  52  35  62]
 [ 94  33  36  72]
 [ 28  49  39  94]
 [ 46  24  71  40]]
Even Numbers:-
 [ 34  50  56 100  52  62  94  36  72  28  94  46  24  40]
Odd Numbers:-
 [65 35 33 49 39 71]
Row-wise Sum:-
 [240 214 235 210 181]
Column-wise Sum:-
 [267 208 237 368]
3D Array:-
 [[[ 34  50  56 100  65]
  [ 52  35  62  94  33]]

 [[ 36  72  28  49  39]
  [ 94  46  24  71  40]]]


In [13]:
import numpy as np

matrix_random = np.random.randint(1, 101, 20).reshape(5, 4)
swap_first_third_row = np.copy(matrix_random)
swap_second_fourth_column = np.copy(matrix_random)
replace_less_50 = np.copy(matrix_random)

print("Original array:\n", matrix_random)

swap_first_third_row[[0, 2]] = swap_first_third_row[[2, 0]]
print("\nArray after swapping first and third rows:\n", swap_first_third_row)

swap_second_fourth_column[:, [1, 3]] = swap_second_fourth_column[:, [3, 1]]
print("\nArray after swapping second and fourth columns:\n", swap_second_fourth_column)

replace_less_50[replace_less_50 < 50] = 0
print("\nArray after replacing values less than 50 with zero:\n", replace_less_50)

array_1d = matrix_random.ravel()
print("\nConverted 1D array:\n", array_1d)


Original array:
 [[42 59 66 37]
 [11 87 44 12]
 [ 3 52 81 33]
 [55  1 39 20]
 [47 43 57 61]]

Array after swapping first and third rows:
 [[ 3 52 81 33]
 [11 87 44 12]
 [42 59 66 37]
 [55  1 39 20]
 [47 43 57 61]]

Array after swapping second and fourth columns:
 [[42 37 66 59]
 [11 12 44 87]
 [ 3 33 81 52]
 [55 20 39  1]
 [47 61 57 43]]

Array after replacing values less than 50 with zero:
 [[ 0 59 66  0]
 [ 0 87  0  0]
 [ 0 52 81  0]
 [55  0  0  0]
 [ 0  0 57 61]]

Converted 1D array:
 [42 59 66 37 11 87 44 12  3 52 81 33 55  1 39 20 47 43 57 61]


In [15]:
import numpy as np

array1 = np.array([5, 6, 7])
array2 = np.array([6, 7, 8])

# Using np.stack() function to stack two arrays column-wise:
array_combined = np.stack((array1, array2), axis=1)

print(array_combined)


[[5 6]
 [6 7]
 [7 8]]


In [19]:
import numpy as np

array1 = np.array([2, 4, 5])
array2 = np.array([9, 8, 2])

arr_combined_hrz = np.stack((array1, array2), axis=0)
arr_combined_vtl = np.stack((array1, array2), axis=1)

print(arr_combined_hrz)
print(arr_combined_vtl)

[[2 4 5]
 [9 8 2]]
[[2 9]
 [4 8]
 [5 2]]


In [20]:
import numpy as np

array1 = np.array([[2, 7, 6],
                [4, 5, 6]])

array2 = np.array([[1, 2, 3],
                [6, 2, 3]])

arr_combined_hrz = np.stack((array1, array2), axis=0)
arr_combined_vtl = np.stack((array1, array2), axis=1)

print(arr_combined_hrz)
print(arr_combined_vtl)


[[[2 7 6]
  [4 5 6]]

 [[1 2 3]
  [6 2 3]]]
[[[2 7 6]
  [1 2 3]]

 [[4 5 6]
  [6 2 3]]]
